export const customers = [
  {
    customerId: 1,
    customerName: 'Acme Corporation',
    customerEmail: 'info@acme.com',
    customerAddress: '123 Industrial Ave, Springfield',
    customerPhone: '0901001001',
    customerFax: '823400001',
    customerFirstName: 'John',
    customerLastName: 'Doe',
    customerSalutation: 'Mr',
    CustomerTypeID: 'CORP',
    CustomerClassId: 'A1',
    CustomerSince: '2015-06-12'
  },
  {
    customerId: 2,
    customerName: 'Globex Ltd.',
    customerEmail: 'contact@globex.com',
    customerAddress: '456 Market Street, Shelbyville',
    customerPhone: '0901001002',
    customerFax: '823400002',
    customerFirstName: 'Mary',
    customerLastName: 'Watson',
    customerSalutation: 'Ms',
    CustomerTypeID: 'CORP',
    CustomerClassId: 'A2',
    CustomerSince: '2018-09-22'
  },
  {
    customerId: 3,
    customerName: 'Initech',
    customerEmail: 'support@initech.com',
    customerAddress: '789 Business Park, Capital City',
    customerPhone: '0901001003',
    customerFax: '823400003',
    customerFirstName: 'Peter',
    customerLastName: 'Gibbons',
    customerSalutation: 'Mr',
    CustomerTypeID: 'BIZ',
    CustomerClassId: 'B1',
    CustomerSince: '2020-01-15'
  },
  {
    customerId: 4,
    customerName: 'Umbrella Corp',
    customerEmail: 'admin@umbrella.com',
    customerAddress: '100 Biohazard Way, Raccoon City',
    customerPhone: '0901001004',
    customerFax: '823400004',
    customerFirstName: 'Alice',
    customerLastName: 'Abernathy',
    customerSalutation: 'Ms',
    CustomerTypeID: 'PHARMA',
    CustomerClassId: 'C1',
    CustomerSince: '2010-03-05'
  },
  {
    customerId: 5,
    customerName: 'Wayne Enterprises',
    customerEmail: 'bruce@wayneenterprises.com',
    customerAddress: '1007 Mountain Drive, Gotham',
    customerPhone: '0901001005',
    customerFax: '823400005',
    customerFirstName: 'Bruce',
    customerLastName: 'Wayne',
    customerSalutation: 'Mr',
    CustomerTypeID: 'VIP',
    CustomerClassId: 'S',
    CustomerSince: '2008-07-19'
  },
  {
    customerId: 6,
    customerName: 'Stark Industries',
    customerEmail: 'tony@starkindustries.com',
    customerAddress: '10880 Malibu Point, Malibu',
    customerPhone: '0901001006',
    customerFax: '823400006',
    customerFirstName: 'Tony',
    customerLastName: 'Stark',
    customerSalutation: 'Mr',
    CustomerTypeID: 'VIP',
    CustomerClassId: 'S',
    CustomerSince: '2002-05-04'
  },
  {
    customerId: 7,
    customerName: 'Wonka Factory',
    customerEmail: 'info@wonka.com',
    customerAddress: '1 Candy Lane, Sweetville',
    customerPhone: '0901001007',
    customerFax: '823400007',
    customerFirstName: 'Willy',
    customerLastName: 'Wonka',
    customerSalutation: 'Mr',
    CustomerTypeID: 'FOOD',
    CustomerClassId: 'B2',
    CustomerSince: '1999-10-31'
  },
  {
    customerId: 8,
    customerName: 'Hooli Inc.',
    customerEmail: 'hello@hooli.com',
    customerAddress: '800 Silicon Ave, Palo Alto',
    customerPhone: '0901001008',
    customerFax: '823400008',
    customerFirstName: 'Gavin',
    customerLastName: 'Belson',
    customerSalutation: 'Mr',
    CustomerTypeID: 'TECH',
    CustomerClassId: 'A3',
    CustomerSince: '2016-11-01'
  },
  {
    customerId: 9,
    customerName: 'Prestige Worldwide',
    customerEmail: 'contact@prestigeworldwide.com',
    customerAddress: '42 Ocean Blvd, Los Angeles',
    customerPhone: '0901001009',
    customerFax: '823400009',
    customerFirstName: 'Brennan',
    customerLastName: 'Huff',
    customerSalutation: 'Mr',
    CustomerTypeID: 'ENT',
    CustomerClassId: 'B3',
    CustomerSince: '2021-02-20'
  },
  {
    customerId: 10,
    customerName: 'Duff Beer Co.',
    customerEmail: 'sales@duffbeer.com',
    customerAddress: '12 Brewery Lane, Springfield',
    customerPhone: '0901001010',
    customerFax: '823400010',
    customerFirstName: 'Homer',
    customerLastName: 'Simpson',
    customerSalutation: 'Mr',
    CustomerTypeID: 'BREW',
    CustomerClassId: 'C2',
    CustomerSince: '2014-08-15'
  },
  {
    customerId: 11,
    customerName: 'Vandelay Industries',
    customerEmail: 'george@vandelay.com',
    customerAddress: '45 Latex Ave, New York',
    customerPhone: '0901001011',
    customerFax: '823400011',
    customerFirstName: 'George',
    customerLastName: 'Costanza',
    customerSalutation: 'Mr',
    CustomerTypeID: 'MFG',
    CustomerClassId: 'C3',
    CustomerSince: '2011-12-10'
  },
  {
    customerId: 12,
    customerName: 'Dunder Mifflin',
    customerEmail: 'sales@dundermifflin.com',
    customerAddress: '1725 Slough Ave, Scranton',
    customerPhone: '0901001012',
    customerFax: '823400012',
    customerFirstName: 'Michael',
    customerLastName: 'Scott',
    customerSalutation: 'Mr',
    CustomerTypeID: 'PAPER',
    CustomerClassId: 'A4',
    CustomerSince: '2005-04-01'
  },
  {
    customerId: 13,
    customerName: 'Oceanic Airlines',
    customerEmail: 'support@oceanic.com',
    customerAddress: 'Terminal 5, Sydney Airport',
    customerPhone: '0901001013',
    customerFax: '823400013',
    customerFirstName: 'Jack',
    customerLastName: 'Shephard',
    customerSalutation: 'Dr',
    CustomerTypeID: 'AIR',
    CustomerClassId: 'A5',
    CustomerSince: '2001-09-11'
  },
  {
    customerId: 14,
    customerName: 'Monsters Inc.',
    customerEmail: 'hello@monstersinc.com',
    customerAddress: '22 Scare Street, Monstropolis',
    customerPhone: '0901001014',
    customerFax: '823400014',
    customerFirstName: 'James',
    customerLastName: 'Sullivan',
    customerSalutation: 'Mr',
    CustomerTypeID: 'ENT',
    CustomerClassId: 'B4',
    CustomerSince: '2012-07-08'
  },
  {
    customerId: 15,
    customerName: 'Cyberdyne Systems',
    customerEmail: 'admin@cyberdyne.com',
    customerAddress: '100 Skynet Blvd, Los Angeles',
    customerPhone: '0901001015',
    customerFax: '823400015',
    customerFirstName: 'Miles',
    customerLastName: 'Dyson',
    customerSalutation: 'Dr',
    CustomerTypeID: 'TECH',
    CustomerClassId: 'A6',
    CustomerSince: '2017-05-09'
  }
];
